jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /restaurante
      session:
         timeout: 21600s
springdoc:
   swagger-ui:
      path: /swagger-ui.html
spring:
   flyway:
      baseline-on-migrate: true
      enabled: true
      locations: classpath:db/migration
   jpa:
      hibernate:
         ddl-auto: none
      # defer-datasource-initialization: true
   h2:
      console:
         enabled: true
         path: /h2
   datasource:
      driver-class-name: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:h2:mem:restaurantedb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
      username: sa
      password: 
      hikari:
         poolName: pool
